name: Build and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main # Set the branch you want to trigger the action on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your AWS region

    - name: Checkout AWS CodeCommit Repository
      run: |
        git config --global credential.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true
        git clone https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sd
        cd sd

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Extract project version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Generate timestamp
      run: echo "TIMESTAMP=$(date +'%Y-%m-%d-%H.%M.%S')" >> $GITHUB_ENV

    - name: Set Version Label
      run: echo "VERSION_LABEL=$VERSION-$TIMESTAMP" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean package -Dartifact-version=$VERSION_LABEL


    - name: Upload artifact to S3
      run: |
        aws s3 cp ${{ github.workspace }}/target/SARTIFACT s3://terraform-s3backend-anatolich911/${{ env.APPLICATION_NAME }}/

   # - name: Create Beanstalk Application Version
   #   run: |
   #     aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $VERSION_LABEL --source-bundle S3Bucket=terraform-s3backend-anatolich911,S3Key=${{ env.APPLICATION_NAME }}/$ARTIFACT

    
