name: Build and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main # Set the branch you want to trigger the action on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your AWS region

    - name: Checkout AWS CodeCommit Repository
      run: |
        git config --global credential.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true
        git clone https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sd
        cd sd

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Extract project version and set environment variables
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        TIMESTAMP=$(date +'%Y-%m-%d-%H.%M.%S')
        VERSION_LABEL="$VERSION-$TIMESTAMP"
        ARTIFACT="$VERSION_LABEL.war"
        APPLICATION_NAME="media-ws" 
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
        echo "VERSION_LABEL=$VERSION_LABEL" >> $GITHUB_ENV
        echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV
        echo "APPLICATION_NAME=$APPLICATION_NAME" >> $GITHUB_ENV

    #- name: Build with Maven
    #  run: mvn clean package -Dartifact-mvt -Dversion.label=$VERSION_LABEL -P code-artifact-mvt


    - name: Upload artifact to S3
      run: aws s3 cp target/$ARTIFACT s3://terraform-s3backend-anatolich911/$APPLICATION_NAME/

    #- name: Create Beanstalk Application Version
    #  run: aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $VERSION_LABEL --source-bundle S3Bucket=elasticbeanstalk-us-east-1-xxxxxxxxxxxx,S3Key=$APPLICATION_NAME/$ARTIFACT

    #- name: Update and deploy to Elastic Beanstalk environments
     # run: |
       #aws elasticbeanstalk update-environment --environment-name $APPLICATION_NAME-media-dev --version-label $VERSION_LABEL
       #aws elasticbeanstalk update-environment --environment-name $APPLICATION_NAME-media-test --version-label $VERSION_LABEL
       #aws elasticbeanstalk update-environment --environment-name $APPLICATION_NAME-media-staging --version-label $VERSION_LABEL
      
    
